### PR TITLE
Switched to NET Standard 2.0 and migrated to SDK-style.

### PR DESCRIPTION
**Pull request by bengtr**
Switched target framework  of FSharp.ViewModule from net45 to netstandard2.0 and net472 for test/example projects. 
Migrated the projects to SDK-style format. Updated dependencies and switched to NUnit3.
Added info to enable in-built VS packaging.

### CODE REVIEW

**Comment by dsyme** [comment]
@ReedCopsey Are you doing maintenance on this? Thanks :)

**Comment by ReedCopsey** [comment]
@dsyme Yes - I'll get this merged and the package updated.

On that note - I noticed the teams were switched around. I'd like to add @bengtr to the maintenance team here - can we put him on the UI team?

**Comment by dsyme** [comment]
Have invited @bengtr as co-maintainer to this repo! :) 
 
Policy-wise I'm not sure about the use of teams - they tend to give over-wide maintenance access - e.g. across all gui projects.  I think per-repo minimized access is more appropriate and more aligned with the intent of the "fsprojects" policies.

Were there other projects you'd like @bengtr added to?

**Comment by ReedCopsey** [comment]
For now, this is probably fine. It's possible he may (at some point) end up wanting to help with FsXaml as well.

**Pull request merged**
